begin;
select no_plan();
insert into auth.users (id,email) values
 ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','jobs-a@example.test'),
 ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','jobs-b@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
insert into public.clients (id,name,herd_number,county,phone,email) values
 ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Job fixture','JOB001','Cork','0000000000','job@example.test');
insert into public.jobs (id,client_id,title) values
 ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Prepare application');
select is((select status from public.jobs),'planned','new jobs start planned');
select is((select count(*)::integer from public.job_events),1,'creation writes history');
select throws_ok($$insert into public.jobs (id,client_id,title) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Prepare application')$$,'23505',null,'replayed creation ID cannot duplicate a job');
select throws_ok($$update public.jobs set status='completed'$$,'23514',null,'cannot skip straight to completed');
select throws_ok($$update public.jobs set status='unknown'$$,'23514',null,'unknown stages rejected');
select throws_ok($$update public.jobs set consultant_id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'$$,'42501',null,'owner is immutable');
select throws_ok($$update public.jobs set client_id='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'$$,'42501',null,'client linkage is immutable');
select throws_ok($$update public.jobs set version=9$$,'42501',null,'version is database controlled');
select throws_ok($$update public.jobs set created_at=now()$$,'42501',null,'timestamps cannot be forged');
select throws_ok($$delete from public.jobs$$,'42501',null,'jobs cannot be permanently deleted by accounts');
update public.jobs set status='in_progress' where version=1;
select is((select version from public.jobs),2,'real changes advance version');
update public.jobs set status='cancelled' where version=1;
select is((select status from public.jobs),'in_progress','stale version changes no rows');
update public.jobs set status='in_progress';
select is((select count(*)::integer from public.job_events),2,'no-op updates do not add history');
update public.jobs set status='completed';
update public.jobs set status='in_progress';
update public.jobs set status='cancelled';
update public.jobs set status='planned';
select is((select count(*)::integer from public.job_events),6,'completion reopening cancellation and replan are recorded');
select throws_ok($$insert into public.jobs (client_id,title,target_date) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Bad date','infinity')$$,'23514',null,'unbounded dates rejected in database');
select throws_ok($$insert into public.jobs (client_id,title) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','   ')$$,'23514',null,'blank titles rejected in database');
select throws_ok($$insert into public.job_events (job_id,client_id,consultant_id,status,version) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','completed',99)$$,'42501',null,'events cannot be forged');
select throws_ok($$update public.job_events set status='completed'$$,'42501',null,'events cannot be edited');
select throws_ok($$delete from public.job_events$$,'42501',null,'events cannot be deleted');
update public.clients set archived_at=now();
select throws_ok($$insert into public.jobs (client_id,title) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Archived client job')$$,'23514',null,'archived clients cannot receive new work');
select throws_ok($$update public.jobs set status='in_progress'$$,'23514',null,'archived client jobs are read-only');
update public.clients set archived_at=null;
select set_config('request.jwt.claim.sub','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',true);
select is((select count(*)::integer from public.jobs),0,'B cannot list A jobs without app filters');
select is((select count(*)::integer from public.jobs where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd'),0,'known job ID does not expose data');
select is((select count(*)::integer from public.job_events),0,'B cannot read A job history');
select throws_ok($$insert into public.jobs (client_id,title) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','Cross-owner job')$$,'23514',null,'B cannot link a job to A client');
select throws_ok($$insert into public.jobs (client_id,consultant_id,title) values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Forged owner')$$,'23514',null,'forged owner rejected before insert');
update public.jobs set status='cancelled' where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select is((select status from public.jobs),'planned','B cannot change A job');
set local role anon;
select throws_ok($$select * from public.jobs$$,'42501',null,'anonymous jobs access denied');
select throws_ok($$select * from public.job_events$$,'42501',null,'anonymous history access denied');
set local role authenticated;
select set_config('request.jwt.claim.sub','',true);
select is((select count(*)::integer from public.jobs),0,'missing identity exposes no jobs');
reset role;
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.jobs'::regclass),'jobs RLS enabled and forced');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.job_events'::regclass),'events RLS enabled and forced');
select * from finish();
rollback;
