begin;
select no_plan();
insert into auth.users (id,email) values
 ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','rates-a@example.test'),
 ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','rates-b@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
insert into public.rates (id,name,unit,price_cents) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Test service','fixed',15025);
select is((select price_cents from public.rates),15025,'exact cents preserved');
select is((select count(*)::integer from public.rate_events),1,'creation logged automatically');
select throws_ok($$insert into public.rates (name,unit,price_cents) values ('Bad','fixed',-1)$$,'23514',null,'negative price rejected');
select throws_ok($$insert into public.rates (name,unit,price_cents) values ('Bad','fixed',100000001)$$,'23514',null,'oversized price rejected');
select throws_ok($$insert into public.rates (name,unit,price_cents) values ('Bad','other',100)$$,'23514',null,'unsupported unit rejected');
select throws_ok($$insert into public.rates (name,unit,price_cents) values ('   ','fixed',100)$$,'23514',null,'blank names rejected');
select throws_ok($$update public.rates set price_cents=1$$,'42501',null,'prices immutable');
select throws_ok($$update public.rates set consultant_id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'$$,'42501',null,'ownership immutable');
select throws_ok($$update public.rates set retired_at=now()$$,'42501',null,'retirement timestamp protected');
select throws_ok($$delete from public.rates$$,'42501',null,'rates cannot be deleted');
select throws_ok($$insert into public.rates (id,name,unit,price_cents) values ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','Test service','fixed',15025)$$,'23505',null,'replay cannot duplicate rate');
select set_config('request.jwt.claim.sub','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',true);
select is((select count(*)::integer from public.rates),0,'B cannot list A rates');
select is((select count(*)::integer from public.rates where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd'),0,'B cannot read known A ID');
select is((select count(*)::integer from public.rate_events),0,'B cannot read A history');
select throws_ok($$insert into public.rates (consultant_id,name,unit,price_cents) values ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Forged','fixed',1)$$,'42501',null,'B cannot forge A ownership');
update public.rates set retired=true where id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
insert into public.rates (name,unit,price_cents) values ('B service','hour',5000);
select is((select count(*)::integer from public.rates),1,'B can access own rate');
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select is((select retired from public.rates),false,'B could not retire A rate');
update public.rates set retired=true;
select ok((select retired_at is not null from public.rates),'retirement timestamp set by database');
update public.rates set retired=true;
select is((select count(*)::integer from public.rate_events),2,'retirement recorded once');
select throws_ok($$update public.rates set retired=false$$,'23514',null,'retired rates cannot be reactivated');
select throws_ok($$delete from public.rate_events$$,'42501',null,'history cannot be deleted');
select throws_ok($$update public.rate_events set action='created'$$,'42501',null,'history cannot be changed');
set local role anon;
select throws_ok($$select * from public.rates$$,'42501',null,'anonymous rates denied');
select throws_ok($$select * from public.rate_events$$,'42501',null,'anonymous history denied');
reset role;
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.rates'::regclass),'rates RLS enabled and forced');
select * from finish();
rollback;
