import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy centre" };

export default function PrivacyCentre() {
  return <div className="mx-auto max-w-5xl space-y-8 px-5 py-8 sm:px-8 lg:py-10">
    <div><p className="eyebrow">Care for the details</p><h1 className="pt-3 text-4xl font-medium tracking-tight">Privacy starts with your practice.</h1><p className="max-w-2xl pt-4 leading-7 text-stone-600">Good records need clear boundaries. Here’s what the demo does, what it doesn’t do, and what needs to happen before real client data belongs here.</p></div>
    <div className="rounded-lg border border-amber-200 bg-amber-50 p-5 text-amber-950"><h2 className="font-medium">Demo only — use fictional client details</h2><p className="pt-2 text-sm leading-6">This is not a GDPR compliance certification. Production hosting, legal notices, retention and operational procedures still need approval.</p></div>
    <div className="grid gap-5 sm:grid-cols-2">
      <section className="panel space-y-3"><h2 className="text-xl font-medium">Separate client books</h2><p className="text-sm leading-6 text-stone-600">Database policies restrict each consultant’s access to their own records. Each server data action also checks the signed-in session. Platform administrators require separate, controlled access.</p></section>
      <section className="panel space-y-3"><h2 className="text-xl font-medium">Less detail on display</h2><p className="text-sm leading-6 text-stone-600">The directory shows names, herd numbers and counties. Open a record to see contact details. Search terms are sent in request bodies, not the browser’s address bar.</p></section>
      <section className="panel space-y-3"><h2 className="text-xl font-medium">Archive is not erasure</h2><p className="text-sm leading-6 text-stone-600">Archived records remain in the database. Agree a retention schedule and review archived clients regularly. This demo does not automatically erase records or expire backups.</p><Link className="button-secondary" href="/clients?status=archived">Review archived clients</Link></section>
      <section className="panel space-y-3"><h2 className="text-xl font-medium">Handle requests carefully</h2><p className="text-sm leading-6 text-stone-600">If a client asks for access, correction or erasure, verify their identity and record the request through your practice’s approved process. Check applicable retention duties before erasing. Bulk export and permanent erasure are not yet self-service features.</p></section>
    </div>
    <section className="panel space-y-5"><div><p className="eyebrow">Before going live</p><h2 className="pt-2 text-2xl font-medium">Your production checklist</h2></div><ol className="list-decimal space-y-4 pl-5 text-sm leading-6 text-stone-700"><li>Identify the responsible organisation and publish an approved privacy notice, including purposes, lawful bases, contact details and rights.</li><li>Approve hosting regions, processor agreements, subprocessors and any international transfers.</li><li>Define retention, secure exports, erasure, account closure and backup expiry procedures.</li><li>Verify email confirmation, password recovery, MFA, session limits, abuse controls and staff access.</li><li>Test backups, incident response and rights requests. Arrange independent security and accessibility reviews.</li></ol></section>
    <section className="panel space-y-3"><h2 className="text-xl font-medium">Database-written activity</h2><p className="text-sm leading-6 text-stone-600">Client profiles show recent changes recorded by the database. Accounts cannot forge, edit or delete those entries, or permanently delete client records directly. History contains event types and field names rather than copies of contact values. Privileged operator access and approved erasure remain separate responsibilities; include history in your retention plan.</p></section>
    <section className="panel space-y-3"><h2 className="text-xl font-medium">Private client work</h2><p className="text-sm leading-6 text-stone-600">Jobs follow the same consultant boundary as clients, enforced in the database. Work titles and planning dates remain client-linked data. Archived clients’ jobs are read-only; cancellation is not erasure. Status history is written automatically and cannot be edited by your account. Include jobs and their history in your retention and rights-request procedures.</p></section>
    <section className="panel space-y-3"><h2 className="text-xl font-medium">Document handling</h2><p className="text-sm leading-6 text-stone-600">PDF filing uses a private storage bucket with database access policies. Downloads are attachments and are not scanned for malware. Use fictional files only, avoid personal details in filenames, and protect downloaded copies. Stored files need their own approved erasure and backup-expiry process; deleting a client does not automatically delete file bytes.</p></section>
    <Link className="button-secondary" href="/privacy">Read demo privacy information</Link>
  </div>;
}
