import { PrivateLink as Link } from "@/components/private-link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy centre" };

const safeguards = [
  ["Database ownership", "Client records, work and private file access are restricted to the owning consultant by database policies. Privileged platform access is a separate responsibility."],
  ["Limited directory data", "The client list contains names, herd numbers and counties. Contact details are fetched when you open a profile. Search terms stay out of the page address."],
  ["Recorded changes", "Database-written client and job history records changes without copying old contact values. Ordinary accounts cannot edit these events. This is not a record of every view or download."],
  ["Private document filing", "PDFs use private storage and authenticated attachment downloads. File checks are not malware scanning; files and downloaded copies need separate retention controls."],
];

const requirements = [
  { title: "Responsible organisation & notice", owner: "Practice owner / legal adviser", detail: "Confirm controller and processor roles, a verified contact, purposes, lawful bases, recipients and rights. Publish an approved notice; do not assume consent is the basis for every activity.", evidence: "Approved notice and record of processing activities." },
  { title: "Hosting & supplier agreements", owner: "Practice owner / hosting administrator", detail: "Approve processing regions, processor contracts, subprocessors, international transfers and privileged support access. Local database tests do not verify hosted settings.", evidence: "Signed agreements, transfer assessment where needed and reviewed hosting configuration." },
  { title: "Retention & client rights", owner: "Practice owner / privacy lead", detail: "Set retention by data category, including jobs, documents, activity history and backups. Establish verified access, correction, export, restriction, objection, erasure and account-closure procedures.", evidence: "Retention schedule and a tested, identity-verified request process." },
  { title: "Account & operational security", owner: "Technical administrator", detail: "Verify production email confirmation, recovery, MFA policy, session limits, abuse controls, HTTPS, credential rotation and staff access reviews.", evidence: "Production configuration review and independent security testing." },
  { title: "Documents & recovery", owner: "Technical administrator / privacy lead", detail: "Approve malware scanning or quarantine, storage quotas, secure file erasure and backup expiry. Deleting a client row does not erase stored file bytes.", evidence: "Tested file-handling, deletion and backup-restore procedures." },
  { title: "Incident response & legal scope", owner: "Practice owner / legal adviser", detail: "Define breach detection and escalation, train staff, assess whether a DPIA is required, and identify applicable Irish/EU, tax, scheme and accessibility obligations for the actual service.", evidence: "Incident exercise, documented risk assessment and applicable-law review." },
];

export default function PrivacyCentre() {
  return <div className="mx-auto max-w-6xl space-y-8 px-5 py-8 sm:px-8 lg:py-10">
    <header className="space-y-3"><p className="eyebrow">Practice / Governance</p><h1 className="text-3xl font-medium tracking-tight sm:text-4xl">Privacy centre</h1><p className="max-w-3xl leading-7 text-stone-600">Implemented safeguards, practical handling guidance and the decisions still required before live use.</p></header>
    <section className="rounded-md border border-amber-200 bg-amber-50 p-5 text-amber-950" aria-labelledby="release-title"><h2 id="release-title" className="font-semibold">Not approved for real client data</h2><p className="pt-2 text-sm leading-6">This demo is not a GDPR certification or an assessment of every applicable regulation. The requirements below remain open. They are not automatically verified, and cannot be completed by ticking a box here.</p></section>
    <nav aria-label="Privacy centre sections" className="section-links"><a className="button-quiet" href="#safeguards">Current safeguards</a><a className="button-quiet" href="#handling">Handle a request</a><a className="button-quiet" href="#release-requirements">Release requirements</a></nav>
    <section id="safeguards" aria-labelledby="safeguards-title" className="space-y-4 scroll-mt-6"><h2 id="safeguards-title" className="text-xl font-medium">Current product safeguards</h2><div className="grid gap-4 sm:grid-cols-2">{safeguards.map(([title, detail]) => <article className="panel space-y-3" key={title}><h3 className="font-medium">{title}</h3><p className="text-sm leading-6 text-stone-600">{detail}</p></article>)}</div></section>
    <section id="handling" aria-labelledby="handling-title" className="panel space-y-5 scroll-mt-6"><h2 id="handling-title" className="text-xl font-medium">Handling a client request</h2><ol className="list-decimal space-y-3 pl-5 text-sm leading-6 text-stone-700"><li>Record when the request arrives in your approved process and verify identity proportionately. Do not request unnecessary identity documents.</li><li>Locate the client and include linked work, history and documents in your assessment. Check third-party information and applicable legal retention obligations.</li><li>Use an approved, secure response channel. Access requests generally require a response within one month; limited extensions have conditions and notification requirements.</li></ol><p className="text-sm leading-6 text-stone-600">Acren does not yet provide a rights-request register, complete export or permanent erasure workflow. Archiving retains records and is not a substitute for erasure.</p><div className="flex flex-wrap gap-3"><Link href="/clients" className="button-secondary">Find a client</Link><Link href="/clients?status=archived" className="button-quiet">Review archived records</Link></div><a className="inline-block text-sm underline underline-offset-4" href="https://www.dataprotection.ie/en/organisations/know-your-obligations/access-and-portability" rel="noreferrer">DPC guidance on access and portability →</a></section>
    <section id="release-requirements" aria-labelledby="requirements-title" className="space-y-4 scroll-mt-6"><div className="space-y-2"><h2 id="requirements-title" className="text-xl font-medium">Production release requirements</h2><p className="text-sm text-stone-600">All six areas require evidence and approval. This is a starting checklist, not an exhaustive legal assessment.</p></div><div className="panel"><ol className="divide-y divide-stone-200">{requirements.map((item, index) => <li key={item.title} className="grid gap-4 py-5 md:grid-cols-[3rem_minmax(0,1fr)_12rem]"><span aria-hidden="true" className="font-mono text-sm text-stone-500">{String(index + 1).padStart(2, "0")}</span><div className="space-y-3"><h3 className="font-medium">{item.title}</h3><p className="text-sm leading-6 text-stone-600">{item.detail}</p><p className="text-sm leading-6"><span className="font-medium">Evidence needed: </span>{item.evidence}</p></div><div className="space-y-2"><p className="text-sm font-semibold text-amber-950">Requires approval</p><p className="text-xs leading-5 text-stone-500">{item.owner}</p></div></li>)}</ol></div></section>
    <footer className="space-y-4 border-t border-stone-200 pt-6"><p className="text-sm leading-6 text-stone-600">Privacy by design includes technical and organisational measures. No visual style, badge or checklist replaces an assessment of your practice and production environment.</p><div className="flex flex-wrap gap-4"><Link className="button-secondary" href="/privacy">Demo privacy information</Link><a className="button-quiet" href="https://www.dataprotection.ie/en/organisations/know-your-obligations/data-security-guidance" rel="noreferrer">DPC security guidance</a><a className="button-quiet" href="https://www.dataprotection.ie/en/organisations/know-your-obligations/transparency" rel="noreferrer">DPC transparency guidance</a></div></footer>
  </div>;
}
