import { PrivateLink as Link } from '@/components/private-link';
import type { Metadata } from 'next';
import { requireSession } from '@/lib/require-session';
import { invoiceNumber,invoiceStatuses } from '@/lib/billing';
import { formatRate } from '@/lib/rates';
import { irelandToday } from '@/lib/work-queue';
export const metadata:Metadata={title:'Invoices'};
export default async function InvoicesPage({searchParams}:{searchParams:Promise<{status?:string;page?:string}>}) {
 const {supabase}=await requireSession();const params=await searchParams;
 const status=params.status&&Object.hasOwn(invoiceStatuses,params.status)?params.status as keyof typeof invoiceStatuses:'issued';
 const page=params.page&&/^\d{1,5}$/.test(params.page)?Math.max(1,Number(params.page)):1;
 const [result,completed]=await Promise.all([supabase.from('invoices').select('id,invoice_number,customer_name,status,total_cents,due_date',{count:'exact'}).eq('status',status).order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1),supabase.from('jobs').select('id,title,client_id').eq('status','completed').order('updated_at',{ascending:false}).order('id').limit(50)]);
 const [linked,clients]=completed.data?.length?await Promise.all([supabase.from('invoices').select('job_id').in('job_id',completed.data.map(j=>j.id)).neq('status','void'),supabase.from('clients').select('id,name,archived_at').in('id',[...new Set(completed.data.map(j=>j.client_id))])]):[null,null];
 const unbilled=completed.data?.filter(j=>!linked?.data?.some(i=>i.job_id===j.id)&&clients?.data?.some(c=>c.id===j.client_id&&!c.archived_at))??[];
 const today=irelandToday(new Date());
 return <div className="mx-auto max-w-6xl space-y-8 px-5 py-8 sm:px-8"><header className="flex flex-wrap items-start justify-between gap-4"><div className="space-y-3"><p className="eyebrow">Practice / Billing</p><h1 className="text-3xl font-medium tracking-tight">Invoices</h1><p className="text-stone-600">Turn completed work into invoices under your business name.</p></div><Link href="/billing" className="button-secondary">Business details</Link></header>
 <section className="panel space-y-4" aria-labelledby="unbilled-title"><h2 id="unbilled-title" className="text-xl font-medium">Completed work to bill</h2><p className="text-xs text-stone-500">Unbilled work for active clients, from your latest 50 completed jobs. Older work is also accessible from each client profile.</p>{completed.error||linked?.error||clients?.error?<p role="alert" className="alert-error">Completed work could not be loaded.</p>:unbilled.length?<ul className="divide-y divide-stone-200">{unbilled.map(j=><li key={j.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0 space-y-1"><p className="break-words font-medium">{j.title}</p><p className="break-words text-sm text-stone-600">{clients?.data?.find(c=>c.id===j.client_id)?.name}</p></div><Link className="button-primary" href={`/invoices/new?job=${j.id}`}>Create invoice</Link></li>)}</ul>:<p className="text-sm text-stone-600">No unbilled work in this recent set. Complete a job from its client profile to bill it.</p>}<Link href="/clients" className="button-quiet">Client book →</Link></section>
 <section className="space-y-5" aria-labelledby="invoice-list-title"><h2 id="invoice-list-title" className="text-xl font-medium">Your invoices</h2><nav aria-label="Invoice status" className="section-links">{Object.entries(invoiceStatuses).map(([key,label])=><Link key={key} className="nav-link" aria-current={status===key?'page':undefined} href={`/invoices?status=${key}`}>{label}</Link>)}</nav>{result.error?<p className="alert-error" role="alert">Invoices could not be loaded. Please refresh.</p>:<><p className="text-sm text-stone-500">{result.count??0} invoices · Page {page}</p><div className="panel">{!result.data?.length?<p>No invoices in this view.</p>:<ul className="divide-y divide-stone-200">{result.data.map(i=><li key={i.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="min-w-0 space-y-1"><Link className="break-words font-medium underline underline-offset-4" href={`/invoices/${i.id}`}>{invoiceNumber(i.invoice_number)} · {i.customer_name}</Link><p className="text-sm text-stone-600">{invoiceStatuses[i.status]}{i.status==='issued'&&i.due_date<today?' · Overdue':''} · Due {i.due_date}</p></div><p className="text-lg tabular-nums">{formatRate(i.total_cents)}</p></li>)}</ul>}</div><nav aria-label="Invoice pages" className="flex justify-between gap-3">{page>1?<Link className="button-secondary" href={`/invoices?status=${status}&page=${page-1}`}>Previous</Link>:<span/>}{page*25<(result.count??0)&&<Link className="button-secondary" href={`/invoices?status=${status}&page=${page+1}`}>Next</Link>}</nav></>}</section><p className="text-xs leading-5 text-stone-500">Invoices are not emailed and Acren does not collect payments. Credit notes and partial payments are not yet supported.</p></div>;
}
