import type { Invoice } from '@/lib/billing';
import { invoiceNumber,invoiceStatuses } from '@/lib/billing';
import { formatRate,rateUnits } from '@/lib/rates';
import { irelandToday } from '@/lib/work-queue';
export function InvoiceSheet({invoice:i}:{invoice:Invoice}) {
 return <article className="invoice-sheet space-y-8" aria-label="Invoice contents"><header className="flex flex-wrap justify-between gap-6"><div className="min-w-0 space-y-2"><h2 className="break-words text-2xl font-medium">{i.supplier_name}</h2><p className="whitespace-pre-wrap break-words text-sm">{i.supplier_address}</p>{i.vat_registered&&<p className="text-sm">VAT registration: {i.supplier_vat_number}</p>}</div><div className="space-y-2"><p className="text-2xl font-medium">{invoiceNumber(i.invoice_number)}</p><p>{invoiceStatuses[i.status]}</p>{i.issued_at&&<p className="text-sm">Issued {irelandToday(new Date(i.issued_at))}</p>}<p className="text-sm">Due {i.due_date}</p></div></header>
 <section className="space-y-2"><h3 className="text-sm font-medium">Bill to</h3><p className="break-words font-medium">{i.customer_name}</p><p className="whitespace-pre-wrap break-words text-sm">{i.customer_address}</p></section>
 <section className="space-y-3 border-y border-current/20 py-5"><h3 className="break-words font-medium">{i.description}</h3><p className="break-words text-sm">{i.rate_name} · {rateUnits[i.unit]}</p><p className="text-sm">Supplied {i.supply_date}</p><dl className="grid grid-cols-2 gap-3 text-sm"><dt>Quantity</dt><dd className="text-right tabular-nums">{i.quantity}</dd><dt>Unit price {i.vat_registered?'(excluding VAT)':''}</dt><dd className="text-right tabular-nums">{formatRate(i.price_cents)}</dd><dt>Net amount</dt><dd className="text-right tabular-nums">{formatRate(i.net_cents)}</dd><dt>{i.vat_registered?`VAT ${(i.vat_basis_points??0)/100}%`:'VAT (not registered)'}</dt><dd className="text-right tabular-nums">{formatRate(i.vat_cents)}</dd><dt className="text-lg font-medium">Total EUR</dt><dd className="text-right text-lg font-medium tabular-nums">{formatRate(i.total_cents)}</dd></dl></section>
 {i.paid_date&&<p className="text-sm">Full payment recorded: {i.paid_date}</p>}{!i.vat_registered&&<p className="text-sm">Supplier is not VAT registered. No VAT charged.</p>}<footer className="space-y-2 text-xs"><p>Demo record · Not for commercial use.</p>{i.status==='draft'&&<p>Draft · No invoice number assigned.</p>}</footer></article>;
}
