import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Demo privacy information" };

export default function PrivacyPage() {
  return <main id="main-content" className="mx-auto max-w-3xl space-y-8 px-5 py-12 sm:px-8"><Link prefetch={false} href="/" className="button-quiet">← Acren</Link><header><p className="eyebrow">Demo privacy information</p><h1 className="pt-3 text-4xl font-medium tracking-tight">Know what you’re putting in.</h1><p className="pt-4 leading-7 text-stone-600">This page describes the demo’s behaviour. It is not the approved privacy notice for a live consultancy service. Use fictional client data only.</p></header>
    <section className="panel space-y-3"><h2 className="text-xl font-medium">Data in this demo</h2><p className="leading-7 text-stone-600">Account email and authentication information are handled by Supabase Auth. Client records contain a name, herd number, county, phone and email, plus ownership, status and timestamps. Do not enter health information, PPS numbers, bank details or other unnecessary information.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-medium">Client activity history</h2><p className="leading-7 text-stone-600">The database records client additions, edits, archives and restores using record and owner identifiers, event types, changed field names and timestamps. Previous contact values are not copied into this history. History is visible only to the owning consultant through the app; privileged platform access is separate. Retention and approved erasure must include these linked events.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-medium">Client jobs</h2><p className="leading-7 text-stone-600">Jobs store a short work title, optional planning date, status, client and owner identifiers, version and timestamps. Job history records creation and status changes without copying the title or contact details into events. These records remain linked to the client and are visible only to the owning consultant through the app. Archiving makes jobs read-only; cancelling a job does not erase it. Include jobs and history in approved retention and rights-request procedures.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-medium">Private document filing</h2><p className="leading-7 text-stone-600">Client PDFs, filenames, owner/client references and upload metadata are retained in a private Supabase Storage bucket. Filenames appear in download addresses and may enter infrastructure logs; use neutral names. The app provides authenticated attachment downloads, not public sharing links. Downloaded copies remain on your device. Files are not malware-scanned: use fictional documents only. Ordinary accounts cannot overwrite or erase files; retention, verified erasure and storage backups require a separate approved process. Deleting a client record does not automatically remove its stored files.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-medium">Cookies and tracking</h2><p className="leading-7 text-stone-600">Sign-in session cookies are used to authenticate requests and refresh your session. Choosing a theme saves an optional preference cookie for 180 days containing only “light” or “dark”; it does not identify your account or track activity. This application adds no analytics or advertising trackers. Hosting and database services may keep operational logs; their production settings and retention still require review.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-medium">Retention and your requests</h2><p className="leading-7 text-stone-600">Archiving keeps a client’s data; it does not delete it. The operator must define retention periods and a secure process for access, correction, export, erasure and account closure before launch. Do not send personal data to an unverified support address.</p></section>
    <section className="rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 className="font-medium">Not ready for real client data</h2><p className="pt-3 leading-7">Controller identity and contact, lawful bases, recipients, processing agreements, rights procedures and production safeguards have not been supplied or verified. These are release blockers, not completed compliance claims.</p></section>
    <p className="text-sm leading-6 text-stone-600">Learn more from the <a className="font-semibold underline underline-offset-4" href="https://www.dataprotection.ie/en/organisations/know-your-obligations/data-security-guidance" rel="noreferrer">Irish Data Protection Commission’s security guidance</a>.</p>
  </main>;
}
